apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wedding-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/daenypark/MCP-Testify.git
    targetRevision: main
    path: ubuntu-20-04.5/k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: wedding-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
  revisionHistoryLimit: 10 