apiVersion: v1
kind: ConfigMap
metadata:
  name: wedding-app-config
  namespace: wedding-app
data:
  SPRING_PROFILES_ACTIVE: "kubernetes"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://wedding-postgres:5432/wedding_db"
  SPRING_DATASOURCE_USERNAME: "wedding_user"
  SPRING_REDIS_HOST: "wedding-redis"
  SPRING_REDIS_PORT: "6379"
  DD_SERVICE: "wedding-api"
  DD_ENV: "development"
  DD_VERSION: "1.0.0"
  DD_PROFILING_ENABLED: "true"
  DD_LOGS_INJECTION: "true" 